language: java
addons:
  sonarcloud:
    organization: "csys-fresher-batch-2019"
    token:
      secure: "83b8bcd691f71f46effa06a392b5482e4b18dcbd"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=csys-fresher-batch-2019_musicapp-seeni
